main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: AUTHOR
description: DESCRIPTION
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
    aliases: example

  kit:
    description: Your description
    usage: /<command>
    permission: example.test

  trade:
    description: Trade
    usage: /trade [Handels ID] (ANZEIGENACHRICHT)

  deltrade:
    description: Trade löschen
    usage: /deltrade [Handels ID]

  showtrades:
    description: Alle Trades zeigen
    usage: /showtrades

permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true

