main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Niclas
description: Trade Plugin für Chris
commands:
  trade:
    description: Trade
    usage: /trade [Handels ID] (ANZEIGENACHRICHT)
    permission: trades

  deltrade:
    description: Trade löschen
    usage: /deltrade [Handels ID]
    permission: trades

  showtrades:
    description: Alle Trades zeigen
    usage: /showtrades
    permission: trades

permissions:
  trades:
    description: Trades Command
    default: true


